"""create question event log table

Revision ID: 20260605_0002
Revises: 20260605_0001
Create Date: 2026-06-05
"""

from alembic import op

revision = "20260605_0002"
down_revision = "20260605_0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS question_events (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            question text NOT NULL,
            ip_address text,
            country text,
            device_type text,
            browser text,
            operating_system text,
            user_agent text,
            request_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
            client_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_question_events_created_at
        ON question_events (created_at DESC)
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS question_events")
