"""create app metadata and knowledge chunk tables

Revision ID: 20260605_0001
Revises:
Create Date: 2026-06-05
"""

import os

from alembic import op
from sqlalchemy import text

revision = "20260605_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS app_versions (
            id boolean PRIMARY KEY DEFAULT true,
            version text NOT NULL,
            updated_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT app_versions_singleton CHECK (id)
        )
        """
    )
    op.get_bind().execute(
        text(
            """
            INSERT INTO app_versions (id, version)
            VALUES (true, :version)
            ON CONFLICT (id) DO NOTHING
            """
        ),
        {"version": os.getenv("APP_VERSION", "0.1.0")},
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS knowledge_chunks (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_path text NOT NULL,
            title text NOT NULL,
            chunk_index integer NOT NULL,
            content text NOT NULL,
            content_hash text NOT NULL,
            embedding vector(1536) NOT NULL,
            embedding_model text NOT NULL,
            created_at timestamptz NOT NULL DEFAULT now(),
            UNIQUE (content_hash, embedding_model)
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS knowledge_chunks")
    op.execute("DROP TABLE IF EXISTS app_versions")
